### PR TITLE
ENHANCEMENT - Add bower link and info to index.hbs about it

### PR DESCRIPTION
**Pull request by triptec**
Added bower link and some info about it.

### CODE REVIEW

**Comment by triptec** [comment]
What was decided? Drop the update to the hbs and keep the bower link in bootstrap?

**Comment by hhff** [comment]
what does `bower link` actually do here?  `npm link` symlinks a package to the local NPM cache so that another package can use it locally without having to connect to NPM.

I'm not sure what `bower link` does - I can use these bootstrap with these packages without it?

**Comment by triptec** [comment]
bower link does the same thing npm link does, like you run "bower link" in spree-ember-auth and then in you new ember app you run "bower link spree-ember-auth" so that it's like you installed it.

**Comment by triptec** [comment]
I needed it for spree-ember-auth, you don't?

**Comment by hhff** [comment]
Not that I'm aware of - but I could be wrong.  Let me do some testing on this first - I'd probably rather re-architect the way it works than to have a dep on bower, as ember-cli want to drop bower eventually

**Comment by hhff** [comment]
also - Travis doesn't seem to need it to run tests?

**Comment by hhff** [comment]
bootstrap.rb is mainly for travis

**Comment by triptec** [comment]
ah

**Pull request closed without merging**
